num1=int(input("enter first number:"))
num2=int(input("enter second number:"))
sum=num1+num2
difference=num1-num2
product=num1*num2
division=num1/num2
modulus=num1%num2
exponent=num1**num2
print(f"sum:{num1}+{num2}={sum}")
print(f"difference:{num1}-{num2}={difference}")
print(f"product:{num1}*{num2}={product}")
print(f"division:{num1}/{num2}={division}")
print("modulus:{num1}%{num2}={modulus}")
print(f"exponent:{num1}**{num2}={exponent}")
